#**Aula Prática de Estatística**
##Aplicação em Python

In [1]:
import pandas as pd
import numpy as np

In [2]:
tabela = pd.read_csv("Dataset_AulaPratica_NOVO.csv", sep = ";", encoding = "iso 8859-1")

In [3]:
tabela

,ID,Altura(cm),Idade,Sexo,Peso(kg),Tam. Calçado,Raça,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1.0,179.0,49.0,M,101.0,41.0,Amarela,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,158.0,18.0,F,52.0,36.0,Parda,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,155.0,21.0,F,54.0,35.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,180.0,21.0,M,63.0,41.0,Parda,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,170.0,20.0,M,75.0,41.0,Parda,NaN,NaN,NaN,NaN,NaN,NaN
5,6.0,172.0,18.0,M,65.0,39.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
6,7.0,177.0,18.0,M,85.0,42.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
7,8.0,184.0,23.0,M,110.0,44.0,Parda,NaN,NaN,NaN,NaN,NaN,NaN
8,9.0,177.0,18.0,M,65.0,41.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
9,10.0,184.0,18.0,M,61.0,41.0,Parda,NaN,NaN,NaN,NaN,NaN,NaN
10,11.0,181.0,21.0,M,112.0,41.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
11,12.0,194.0,20.0,M,69.0,43.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
12,13.0,195.0,18.0,M,70.0,44.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
13,14.0,182.0,18.0,M,73.0,43.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
14,15.0,184.0,18.0,M,83.0,42.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
15,16.0,168.0,20.0,M,63.0,41.0,Parda,NaN,NaN,NaN,NaN,NaN,NaN
16,17.0,170.0,19.0,M,78.0,38.0,Amarela,NaN,NaN,NaN,NaN,NaN,NaN
17,18.0,173.0,36.0,M,85.0,40.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
18,19.0,175.0,19.0,M,71.0,40.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
19,20.0,177.0,58.0,M,108.0,42.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
20,21.0,180.0,31.0,M,69.0,40.0,Parda,NaN,NaN,NaN,NaN,NaN,NaN
21,22.0,180.0,18.0,M,54.0,42.0,Parda,NaN,NaN,NaN,NaN,NaN,NaN
22,23.0,182.0,19.0,M,78.0,44.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
23,24.0,186.0,23.0,M,93.0,43.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
24,25.0,178.0,17.0,M,76.0,43.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
25,26.0,191.0,21.0,M,65.0,43.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
26,27.0,180.0,18.0,M,73.0,43.0,Parda,NaN,NaN,NaN,NaN,NaN,NaN
27,28.0,170.0,17.0,M,67.0,41.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
28,29.0,161.0,19.0,F,66.0,36.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
29,30.0,182.0,20.0,M,68.0,41.0,Parda,NaN,NaN,NaN,NaN,NaN,NaN
30,31.0,175.0,25.0,M,67.0,41.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
31,32.0,162.0,21.0,M,54.0,38.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
32,33.0,180.0,19.0,M,74.0,43.0,Parda,NaN,NaN,NaN,NaN,NaN,NaN
33,34.0,173.0,19.0,M,68.0,41.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
34,35.0,181.0,18.0,M,58.0,42.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
35,36.0,177.0,19.0,M,74.0,41.0,Parda,NaN,NaN,NaN,NaN,NaN,NaN
36,37.0,170.0,21.0,M,57.0,40.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
37,38.0,167.0,21.0,M,68.0,40.0,Parda,NaN,NaN,NaN,NaN,NaN,NaN
38,39.0,171.0,18.0,M,70.0,41.0,Parda,NaN,NaN,NaN,NaN,NaN,NaN
39,40.0,181.0,19.0,M,96.0,42.0,Parda,NaN,NaN,NaN,NaN,NaN,NaN
40,41.0,178.0,37.0,M,90.0,42.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
41,42.0,185.0,19.0,M,73.0,42.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
42,43.0,196.0,22.0,M,116.0,44.0,Branca,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Remover as colunas 'Unnamed: 7' até 'Unnamed: 12'
tabela = tabela.drop(tabela.columns[7:13], axis=1)

# Remover as linhas com id >= 44
tabela = tabela[tabela['ID'] < 44]

In [5]:
tabela

      ID  Altura(cm)  Idade Sexo  Peso(kg)  Tam. Calçado     Raça
0    1.0       179.0   49.0    M     101.0          41.0  Amarela
1    2.0       158.0   18.0    F      52.0          36.0    Parda
2    3.0       155.0   21.0    F      54.0          35.0   Branca
3    4.0       180.0   21.0    M      63.0          41.0    Parda
4    5.0       170.0   20.0    M      75.0          41.0    Parda
5    6.0       172.0   18.0    M      65.0          39.0   Branca
6    7.0       177.0   18.0    M      85.0          42.0   Branca
7    8.0       184.0   23.0    M     110.0          44.0    Parda
8    9.0       177.0   18.0    M      65.0          41.0   Branca
9   10.0       184.0   18.0    M      61.0          41.0    Parda
10  11.0       181.0   21.0    M     112.0          41.0   Branca
11  12.0       194.0   20.0    M      69.0          43.0   Branca
12  13.0       195.0   18.0    M      70.0          44.0   Branca
13  14.0       182.0   18.0    M      73.0          43.0   Branca
14  15.0       184.0   18.0    M      83.0          42.0   Branca
15  16.0       168.0   20.0    M      63.0          41.0    Parda
16  17.0       170.0   19.0    M      78.0          38.0  Amarela
17  18.0       173.0   36.0    M      85.0          40.0   Branca
18  19.0       175.0   19.0    M      71.0          40.0   Branca
19  20.0       177.0   58.0    M     108.0          42.0   Branca
20  21.0       180.0   31.0    M      69.0          40.0    Parda
21  22.0       180.0   18.0    M      54.0          42.0    Parda
22  23.0       182.0   19.0    M      78.0          44.0   Branca
23  24.0       186.0   23.0    M      93.0          43.0   Branca
24  25.0       178.0   17.0    M      76.0          43.0   Branca
25  26.0       191.0   21.0    M      65.0          43.0   Branca
26  27.0       180.0   18.0    M      73.0          43.0    Parda
27  28.0       170.0   17.0    M      67.0          41.0   Branca
28  29.0       161.0   19.0    F      66.0          36.0   Branca
29  30.0       182.0   20.0    M      68.0          41.0    Parda
30  31.0       175.0   25.0    M      67.0          41.0   Branca
31  32.0       162.0   21.0    M      54.0          38.0   Branca
32  33.0       180.0   19.0    M      74.0          43.0    Parda
33  34.0       173.0   19.0    M      68.0          41.0   Branca
34  35.0       181.0   18.0    M      58.0          42.0   Branca
35  36.0       177.0   19.0    M      74.0          41.0    Parda
36  37.0       170.0   21.0    M      57.0          40.0   Branca
37  38.0       167.0   21.0    M      68.0          40.0    Parda
38  39.0       171.0   18.0    M      70.0          41.0    Parda
39  40.0       181.0   19.0    M      96.0          42.0    Parda
40  41.0       178.0   37.0    M      90.0          42.0   Branca
41  42.0       185.0   19.0    M      73.0          42.0   Branca
42  43.0       196.0   22.0    M     116.0          44.0   Branca

In [6]:
# Calcular o valor médio da variável Altura(cm)
valor_medio_altura = tabela['Altura(cm)'].mean()

print(f"O valor médio da variável Altura(cm) é: {valor_medio_altura:.2f}")

O valor médio da variável Altura(cm) é: 177.23

In [7]:
# Calcular o valor médio da variável idade
media_idade = tabela['Idade'].mean()

print(f"O valor médio da variável idade é: {media_idade:.0f}")

O valor médio da variável idade é: 22

In [8]:
 # Calcular o valor médio da variável idade
media_calcado = tabela["Tam. Calçado"].mean()

print(f"O valor médio da variável idade é: {media_calcado:.0f}")

O valor médio da variável idade é: 41

In [9]:
# Calcular o IMC (Índice de Massa Corporal)
tabela['IMC'] = tabela['Peso(kg)'] / ((tabela['Altura(cm)'] / 100) ** 2)

In [10]:
tabela["IMC"]

0     31.522112
1     20.829995
2     22.476587
3     19.444444
4     25.951557
5     21.971336
6     27.131412
7     32.490548
8     20.747550
9     18.017486
10    34.186991
11    18.333510
12    18.408941
13    22.038401
14    24.515595
15    22.321429
16    26.989619
17    28.400548
18    23.183673
19    34.472853
20    21.296296
21    16.666667
22    23.547881
23    26.881720
24    23.986870
25    17.817494
26    22.530864
27    23.183391
28    25.461981
29    20.528922
30    21.877551
31    20.576132
32    22.839506
33    22.720438
34    17.703977
35    23.620288
36    19.723183
37    24.382373
38    23.938990
39    29.303135
40    28.405504
41    21.329438
42    30.195752
Name: IMC, dtype: float64

In [11]:
def classificar_imc(imc):
    if imc < 18.5:
        return 'Abaixo do peso'
    elif 18.5 <= imc < 25:
        return 'Peso normal'
    elif 25 <= imc < 30:
        return 'Sobrepeso'
    elif 30 <= imc < 35:
        return 'Obesidade Grau I'
    elif 35 <= imc < 40:
        return 'Obesidade Grau II (severa)'
    else:
        return 'Obesidade Grau III (mórbida)'

# Adicionando uma nova coluna com a classificação de IMC
tabela['Classificação_IMC'] = tabela['IMC'].apply(classificar_imc)

# Exibindo as primeiras linhas do DataFrame com a nova coluna
print(tabela[['IMC', 'Classificação_IMC']])

          IMC Classificação_IMC
0   31.522112  Obesidade Grau I
1   20.829995       Peso normal
2   22.476587       Peso normal
3   19.444444       Peso normal
4   25.951557         Sobrepeso
5   21.971336       Peso normal
6   27.131412         Sobrepeso
7   32.490548  Obesidade Grau I
8   20.747550       Peso normal
9   18.017486    Abaixo do peso
10  34.186991  Obesidade Grau I
11  18.333510    Abaixo do peso
12  18.408941    Abaixo do peso
13  22.038401       Peso normal
14  24.515595       Peso normal
15  22.321429       Peso normal
16  26.989619         Sobrepeso
17  28.400548         Sobrepeso
18  23.183673       Peso normal
19  34.472853  Obesidade Grau I
20  21.296296       Peso normal
21  16.666667    Abaixo do peso
22  23.547881       Peso normal
23  26.881720         Sobrepeso
24  23.986870       Peso normal
25  17.817494    Abaixo do peso
26  22.530864       Peso normal
27  23.183391       Peso normal
28  25.461981         Sobrepeso
29  20.528922       Peso normal
30  21.877551       Peso normal
31  20.576132       Peso normal
32  22.839506       Peso normal
33  22.720438       Peso normal
34  17.703977    Abaixo do peso
35  23.620288       Peso normal
36  19.723183       Peso normal
37  24.382373       Peso normal
38  23.938990       Peso normal
39  29.303135         Sobrepeso
40  28.405504         Sobrepeso
41  21.329438       Peso normal
42  30.195752  Obesidade Grau I